blank_issues_enabled: false
contact_links:
  - name: Eastern Townhall Community Support
    url: https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/discussions
    about: Please ask and answer questions here.