name: Site Smoke Run

on: 
  pull_request:

jobs:
  terraform:
    name: "Hugo Test Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs:        true
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        id: dpn
        run: npm ci
      
      - name: Build Hugo 
        id: bld
        run: hugo --minify

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        env:
          PLAN: "Hugo\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Github Checkout 🖌\`${{ steps.chk.outcome }}\`
            #### Hugo dependencies ⚙️\`${{ steps.dpn.outcome }}\`
            #### Install dependencies 📖\`${{ steps.dpn.outcome }}\`
            #### Hugo Build 🤖\`${{ steps.bld.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Hugo Build Status
        if: steps.plan.outcome == 'failure'
        run: exit 1